// ---------------------------------------------------------------------------
// Adversarial / property coverage for `src/features/setup/rotationEditing.ts`
// (COMPONENTS.md §14, §15.3/G4).
//
// The colocated `RotationEditor.test.ts` asserts the documented behaviour on
// hand-picked sequences. This file tries to BREAK the documented invariants
// over exhaustively enumerated sequences instead, so a counterexample is found
// by search rather than by having been anticipated.
//
// Determinism: every sequence here is generated by a fixed enumeration over a
// fixed alphabet. There is no RNG, no clock and no ordering dependence.
// ---------------------------------------------------------------------------

import { describe, expect, it } from "vitest";
import type { CharacterDefinition, Rotation, RotationAction } from "@/types";
import { characters } from "@/game-data";
import {
  ADDABLE_ACTION_TYPES,
  actionDuration,
  announceInsert,
  clampSelection,
  deleteAction,
  duplicateAction,
  indexAfterNormalize,
  insertAction,
  insertionIndex,
  missingSwapIndexes,
  moveAction,
  needsAutoSwap,
  normalizeSwaps,
  redundantSwapIndexes,
  rowTimings,
  selectionAfterDelete,
  summarizeRotation,
  type AddableActionType,
} from "@/features/setup/rotationEditing";

function required(id: string): CharacterDefinition {
  const found = characters.find((c) => c.id === id);
  if (found === undefined) throw new Error(`missing test character "${id}"`);
  return found;
}

const A = required("bennett");
const B = required("xiangling");
const C = required("xingqiu");

const byId = new Map<string, CharacterDefinition>([
  [A.id, A],
  [B.id, B],
  [C.id, C],
]);

/**
 * The generation alphabet: three characters x {swap, skill, burst}.
 *
 * Three actors is the smallest size that can express "swap away and back",
 * which is the case a two-actor alphabet cannot distinguish from a no-op.
 */
const ALPHABET: readonly RotationAction[] = [A, B, C].flatMap((character) =>
  (["swap", "skill", "burst"] as const).map((actionType) =>
    actionType === "swap"
      ? ({ characterId: character.id, actionType } as RotationAction)
      : ({
          characterId: character.id,
          actionType,
          abilityId:
            actionType === "skill"
              ? character.elementalSkill.id
              : character.elementalBurst.id,
        } as RotationAction),
  ),
);

/** Every sequence of length `0..maxLength` over `ALPHABET`, in a fixed order. */
function enumerateRotations(maxLength: number): readonly Rotation[] {
  let level: Rotation[] = [[]];
  const all: Rotation[] = [[]];
  for (let length = 1; length <= maxLength; length += 1) {
    const next: Rotation[] = [];
    for (const prefix of level) {
      for (const action of ALPHABET) next.push([...prefix, action]);
    }
    all.push(...next);
    level = next;
  }
  return all;
}

/** 9^0 + 9^1 + 9^2 + 9^3 = 820 sequences. */
const ALL_ROTATIONS = enumerateRotations(3);

function key(action: RotationAction): string {
  return `${action.characterId}:${action.actionType}`;
}

function keys(rotation: Rotation): readonly string[] {
  return rotation.map(key);
}

/** Who is on field after executing `rotation`, ignoring reachability. */
function activeAfter(rotation: Rotation): string | undefined {
  return rotation[rotation.length - 1]?.characterId;
}

describe("normalizeSwaps invariants (§14.6) — enumerated over 820 sequences", () => {
  it("never inserts, never reorders and never removes a non-swap", () => {
    for (const rotation of ALL_ROTATIONS) {
      const next = normalizeSwaps(rotation);

      expect(next.length).toBeLessThanOrEqual(rotation.length);

      // Remove-only: the output is a SUBSEQUENCE of the input, and every
      // surviving row is the identical object from the input. This rules out
      // insertion, reordering and mutation in one assertion.
      let cursor = 0;
      for (const action of next) {
        while (cursor < rotation.length && rotation[cursor] !== action) {
          cursor += 1;
        }
        expect(cursor).toBeLessThan(rotation.length);
        cursor += 1;
      }

      // Nothing but a `swap` is ever dropped.
      const droppedNonSwaps = rotation
        .filter((_, i) => !new Set(redundantSwapIndexes(rotation)).has(i))
        .filter((a) => a.actionType !== "swap").length;
      expect(droppedNonSwaps).toBe(
        rotation.filter((a) => a.actionType !== "swap").length,
      );
    }
  });

  it("is idempotent: normalize(normalize(x)) === normalize(x)", () => {
    for (const rotation of ALL_ROTATIONS) {
      const once = normalizeSwaps(rotation);
      const twice = normalizeSwaps(once);
      expect(keys(twice)).toEqual(keys(once));
      // A second pass must find nothing left to remove.
      expect(redundantSwapIndexes(once)).toEqual([]);
    }
  });

  it("preserves who is on field at the end of the sequence", () => {
    // A removed swap is by definition a no-op, so the final active character
    // cannot change. The ONE exception is a sequence that is nothing but a
    // leading swap: `[⇄ A]` reaps to `[]`, which has no active character. That
    // is the documented index-0 rule, not a stranded real swap.
    for (const rotation of ALL_ROTATIONS) {
      const next = normalizeSwaps(rotation);
      if (next.length === 0 && rotation.length > 0) {
        expect(rotation.every((a) => a.actionType === "swap")).toBe(true);
        continue;
      }
      expect(activeAfter(next)).toBe(activeAfter(rotation));
    }
  });

  it("never removes a TRAILING swap that changes who is on field", () => {
    for (const rotation of ALL_ROTATIONS) {
      const last = rotation[rotation.length - 1];
      if (last === undefined || last.actionType !== "swap") continue;
      // Judge against the PREFIX AS NORMALIZED. In `[⇄ A, ⇄ B]` the leading
      // swap is reaped by the index-0 rule, which leaves `⇄ B` opening the
      // sequence and therefore genuinely redundant too. Comparing against the
      // raw previous row would call that a stranded real swap.
      const normalizedPrefix = normalizeSwaps(rotation.slice(0, -1));
      const previousActor = activeAfter(normalizedPrefix);
      if (previousActor === undefined || previousActor === last.characterId) {
        continue; // genuinely redundant; reaping it is correct
      }
      const next = normalizeSwaps(rotation);
      expect(next[next.length - 1]).toBe(last);
    }
  });

  it("reaps a LEADING swap: the first actor is on field, never swapped in", () => {
    const rotation: Rotation = [
      { characterId: A.id, actionType: "swap" },
      { characterId: A.id, actionType: "skill" },
    ];
    expect(redundantSwapIndexes(rotation)).toEqual([0]);
    expect(normalizeSwaps(rotation).map(key)).toEqual([`${A.id}:skill`]);
  });

  it("deleting the first action reaps the swap it made necessary", () => {
    // §14.6 end to end: `A skill, ⇄ B, B skill` minus its first row leaves B
    // as the opening actor, so the swap to B is no longer doing work.
    const rotation: Rotation = [
      { characterId: A.id, actionType: "skill" },
      { characterId: B.id, actionType: "swap" },
      { characterId: B.id, actionType: "skill" },
    ];
    expect(deleteAction(rotation, 0).map(key)).toEqual([`${B.id}:skill`]);
    expect(missingSwapIndexes(deleteAction(rotation, 0))).toEqual([]);
  });

  it("moving a swap to the front reaps it and exposes the now-unreachable row", () => {
    const rotation: Rotation = [
      { characterId: A.id, actionType: "skill" },
      { characterId: B.id, actionType: "swap" },
      { characterId: B.id, actionType: "skill" },
    ];
    const moved = moveAction(rotation, 1, 0);
    expect(moved.map(key)).toEqual([`${A.id}:skill`, `${B.id}:skill`]);
    // The row is left visibly wrong rather than silently repaired (§14.6).
    expect(missingSwapIndexes(moved)).toEqual([1]);
  });

  it("removes exactly the swaps that are no-ops at their own position", () => {
    for (const rotation of ALL_ROTATIONS) {
      const flagged = new Set(redundantSwapIndexes(rotation));
      let active: string | undefined;
      rotation.forEach((action, index) => {
        if (action.actionType === "swap") {
          const isNoOp = active === undefined || active === action.characterId;
          expect(flagged.has(index)).toBe(isNoOp);
          if (isNoOp) return;
        } else {
          expect(flagged.has(index)).toBe(false);
        }
        active = action.characterId;
      });
    }
  });

  it("never CREATES an unreachable row by removing a swap", () => {
    // The safety direction: normalization may only make the sequence more
    // reachable (by reaping a leading swap that was blocking the opener), never
    // less. A count that GREW would mean a load-bearing swap was reaped.
    for (const rotation of ALL_ROTATIONS) {
      const before = missingSwapIndexes(rotation).length;
      const after = missingSwapIndexes(normalizeSwaps(rotation)).length;
      expect(after).toBeLessThanOrEqual(before);
    }
  });

  it("only the index-0 rule may lower the unreachable count", () => {
    // Pins the ONE asymmetry found by enumeration: `[⇄ A, B skill]` reports one
    // unreachable row, and reaping the leading swap drops that report to zero
    // because B becomes the opening actor. Anywhere the leading row is not a
    // reaped swap, the count must be exactly preserved.
    for (const rotation of ALL_ROTATIONS) {
      const leadingSwapReaped = redundantSwapIndexes(rotation).includes(0);
      if (leadingSwapReaped) continue;
      expect(missingSwapIndexes(normalizeSwaps(rotation)).length).toBe(
        missingSwapIndexes(rotation).length,
      );
    }
  });
});

describe("index arithmetic under composition — enumerated", () => {
  it("indexAfterNormalize never escapes the normalized array", () => {
    for (const rotation of ALL_ROTATIONS) {
      const next = normalizeSwaps(rotation);
      for (let i = 0; i < rotation.length; i += 1) {
        const mapped = indexAfterNormalize(rotation, i);
        expect(mapped).toBeGreaterThanOrEqual(0);
        expect(mapped).toBeLessThanOrEqual(next.length);
      }
    }
  });

  it("indexAfterNormalize points at the SAME action when that row survives", () => {
    for (const rotation of ALL_ROTATIONS) {
      const dropped = new Set(redundantSwapIndexes(rotation));
      const next = normalizeSwaps(rotation);
      for (let i = 0; i < rotation.length; i += 1) {
        if (dropped.has(i)) continue;
        expect(next[indexAfterNormalize(rotation, i)]).toBe(rotation[i]);
      }
    }
  });

  it("clampSelection returns null or a valid index, for any integer input", () => {
    const probes = [-1000, -2, -1, 0, 1, 2, 3, 5, 1000];
    for (const rotation of ALL_ROTATIONS) {
      for (const probe of probes) {
        const clamped = clampSelection(rotation, probe);
        if (rotation.length === 0) {
          expect(clamped).toBeNull();
          continue;
        }
        expect(clamped).not.toBeNull();
        expect(clamped as number).toBeGreaterThanOrEqual(0);
        expect(clamped as number).toBeLessThan(rotation.length);
        expect(rotation[clamped as number]).toBeDefined();
      }
    }
  });

  it("selectionAfterDelete never points past the shortened list", () => {
    for (const rotation of ALL_ROTATIONS) {
      for (let i = 0; i < rotation.length; i += 1) {
        const after = deleteAction(rotation, i);
        const selection = selectionAfterDelete(after.length, i);
        if (after.length === 0) {
          expect(selection).toBeNull();
          continue;
        }
        expect(selection).not.toBeNull();
        expect(after[selection as number]).toBeDefined();
      }
    }
  });

  it("insertionIndex is always a legal splice position", () => {
    for (const rotation of ALL_ROTATIONS) {
      for (const probe of [null, -5, -1, 0, 1, 2, 3, 99] as const) {
        const index = insertionIndex(rotation, probe);
        expect(index).toBeGreaterThanOrEqual(0);
        expect(index).toBeLessThanOrEqual(rotation.length);
      }
    }
  });
});

describe("insertAction — enumerated over sequence x cursor x character x type", () => {
  it("always returns an actionIndex that holds the authored action", () => {
    for (const rotation of enumerateRotations(2)) {
      for (let cursor = 0; cursor <= rotation.length; cursor += 1) {
        for (const character of [A, B, C]) {
          for (const actionType of ADDABLE_ACTION_TYPES) {
            const result = insertAction(
              rotation,
              cursor,
              character,
              actionType,
            );
            const landed = result.rotation[result.actionIndex];
            expect(landed).toBeDefined();
            expect(landed?.characterId).toBe(character.id);
            expect(landed?.actionType).toBe(actionType);
          }
        }
      }
    }
  });

  it("never produces a redundant swap and never loses a pre-existing non-swap", () => {
    for (const rotation of enumerateRotations(2)) {
      const nonSwapsBefore = rotation.filter(
        (a) => a.actionType !== "swap",
      ).length;
      for (let cursor = 0; cursor <= rotation.length; cursor += 1) {
        const result = insertAction(rotation, cursor, C, "burst");
        expect(redundantSwapIndexes(result.rotation)).toEqual([]);
        expect(
          result.rotation.filter((a) => a.actionType !== "swap").length,
        ).toBe(nonSwapsBefore + 1);
      }
    }
  });

  it("judges the actor AT THE CURSOR, not at the end of the list (§14.6)", () => {
    // Cursor sits after A's skill; the list ENDS on B. A swap must NOT be
    // inserted for A, because A is the actor at the cursor.
    const rotation: Rotation = [
      { characterId: A.id, actionType: "skill" },
      { characterId: B.id, actionType: "swap" },
      { characterId: B.id, actionType: "burst" },
    ];
    expect(needsAutoSwap(rotation, 1, A.id)).toBe(false);
    const result = insertAction(rotation, 1, A, "normal");
    expect(result.autoSwapped).toBe(false);
    expect(result.insertedCount).toBe(1);
    // The later swap to B still does real work and must survive.
    expect(result.rotation.map(key)).toEqual([
      `${A.id}:skill`,
      `${A.id}:normal`,
      `${B.id}:swap`,
      `${B.id}:burst`,
    ]);
  });

  it("never auto-swaps at index 0 of any sequence, including an empty one", () => {
    for (const rotation of enumerateRotations(3)) {
      for (const character of [A, B, C]) {
        expect(needsAutoSwap(rotation, 0, character.id)).toBe(false);
        expect(insertAction(rotation, 0, character, "skill").autoSwapped).toBe(
          false,
        );
      }
    }
  });

  it("strands no swap when the insert makes a later swap a no-op", () => {
    // Inserting `B skill` between `⇄ B` and `B burst`: the leading swap is
    // still needed, nothing should be reaped.
    const rotation: Rotation = [
      { characterId: A.id, actionType: "skill" },
      { characterId: B.id, actionType: "swap" },
      { characterId: B.id, actionType: "burst" },
    ];
    const result = insertAction(rotation, 2, B, "skill");
    expect(result.autoSwapped).toBe(false);
    expect(result.rotation.map(key)).toEqual([
      `${A.id}:skill`,
      `${B.id}:swap`,
      `${B.id}:skill`,
      `${B.id}:burst`,
    ]);
    expect(result.rotation[result.actionIndex]?.actionType).toBe("skill");
  });
});

describe("moveAction / deleteAction / duplicateAction boundaries", () => {
  const rotation: Rotation = [
    { characterId: A.id, actionType: "skill" },
    { characterId: A.id, actionType: "normal" },
    { characterId: A.id, actionType: "burst" },
  ];

  it("moveAction with an out-of-range source is a no-op returning the same array", () => {
    for (const from of [-1, -99, 3, 99]) {
      expect(moveAction(rotation, from, 0)).toBe(rotation);
    }
  });

  it("moveAction clamps an out-of-range destination into the array", () => {
    expect(moveAction(rotation, 0, 99).map(key)).toEqual([
      `${A.id}:normal`,
      `${A.id}:burst`,
      `${A.id}:skill`,
    ]);
    expect(moveAction(rotation, 2, -99).map(key)).toEqual([
      `${A.id}:burst`,
      `${A.id}:skill`,
      `${A.id}:normal`,
    ]);
  });

  it("moveAction onto itself returns the identical array", () => {
    for (let i = 0; i < rotation.length; i += 1) {
      expect(moveAction(rotation, i, i)).toBe(rotation);
    }
  });

  it("moveAction is length-preserving except for reaped no-op swaps", () => {
    for (const source of enumerateRotations(3)) {
      for (let from = 0; from < source.length; from += 1) {
        for (let to = 0; to < source.length; to += 1) {
          const next = moveAction(source, from, to);
          expect(next.length).toBeLessThanOrEqual(source.length);
          expect(
            next.filter((a) => a.actionType !== "swap").length,
          ).toBe(source.filter((a) => a.actionType !== "swap").length);
          if (from === to) {
            // A no-op move short-circuits BEFORE normalizing, so it returns the
            // input untouched rather than a normalized copy. Harmless only
            // because it cannot change the sequence; pinned so the
            // short-circuit is not mistaken for a normalization guarantee.
            expect(next).toBe(source);
            continue;
          }
          expect(redundantSwapIndexes(next)).toEqual([]);
        }
      }
    }
  });

  it("deleteAction on the only row empties the list", () => {
    const single: Rotation = [{ characterId: A.id, actionType: "skill" }];
    expect(deleteAction(single, 0)).toEqual([]);
    expect(selectionAfterDelete(0, 0)).toBeNull();
  });

  it("deleteAction of the last row selects the new last row", () => {
    const after = deleteAction(rotation, 2);
    expect(after).toHaveLength(2);
    expect(selectionAfterDelete(after.length, 2)).toBe(1);
  });

  it("deleteAction with an out-of-range index is a no-op returning the same array", () => {
    for (const index of [-1, -99, 3, 99]) {
      expect(deleteAction(rotation, index)).toBe(rotation);
    }
  });

  it("deleteAction removes exactly one non-swap, for every index of every sequence", () => {
    for (const source of enumerateRotations(3)) {
      for (let i = 0; i < source.length; i += 1) {
        const next = deleteAction(source, i);
        const removedNonSwap = source[i]?.actionType !== "swap" ? 1 : 0;
        expect(next.filter((a) => a.actionType !== "swap").length).toBe(
          source.filter((a) => a.actionType !== "swap").length - removedNonSwap,
        );
        expect(redundantSwapIndexes(next)).toEqual([]);
      }
    }
  });

  it("duplicateAction at the last index appends a copy, not a shared reference", () => {
    const next = duplicateAction(rotation, 2);
    expect(next.map(key)).toEqual([
      `${A.id}:skill`,
      `${A.id}:normal`,
      `${A.id}:burst`,
      `${A.id}:burst`,
    ]);
    expect(next[3]).not.toBe(rotation[2]);
  });

  it("duplicateAction of a swap is a no-op: the copy would always be redundant", () => {
    const withSwap: Rotation = [
      { characterId: A.id, actionType: "skill" },
      { characterId: B.id, actionType: "swap" },
    ];
    expect(duplicateAction(withSwap, 1).map(key)).toEqual(keys(withSwap));
  });

  it("duplicateAction with an out-of-range index is a no-op", () => {
    for (const index of [-1, 3, 99]) {
      expect(duplicateAction(rotation, index)).toBe(rotation);
    }
  });
});

describe("swapCost threading (§15.3/G4) — the configured value, never a constant", () => {
  const COSTS = [0, 0.4, 0.6, 1.25, 3] as const;
  const swapRow: RotationAction = { characterId: B.id, actionType: "swap" };

  it("actionDuration prices a swap at exactly the supplied cost", () => {
    for (const cost of COSTS) {
      expect(actionDuration(swapRow, B, cost)).toBe(cost);
      // A swap is priced even when the character is NOT in the team: the cost
      // belongs to the swap, not to the actor.
      expect(actionDuration(swapRow, undefined, cost)).toBe(cost);
    }
  });

  it("rowTimings advances the clock by the supplied cost", () => {
    const rotation: Rotation = [
      { characterId: A.id, actionType: "skill" },
      swapRow,
      { characterId: B.id, actionType: "burst" },
    ];
    for (const cost of COSTS) {
      const timings = rowTimings(rotation, byId, cost);
      expect(timings[1]?.duration).toBe(cost);
      expect(timings[2]?.startTime).toBeCloseTo(
        A.elementalSkill.castTime + cost,
        10,
      );
    }
  });

  it("summarizeRotation's swapSeconds and totalSeconds both use the supplied cost", () => {
    const rotation: Rotation = [
      { characterId: A.id, actionType: "skill" },
      swapRow,
      { characterId: B.id, actionType: "burst" },
    ];
    for (const cost of COSTS) {
      const summary = summarizeRotation(rotation, byId, cost);
      expect(summary.swapCount).toBe(1);
      expect(summary.swapSeconds).toBeCloseTo(cost, 10);
      expect(summary.totalSeconds).toBeCloseTo(
        A.elementalSkill.castTime + cost + B.elementalBurst.castTime,
        10,
      );
    }
  });

  it("the header total and the per-row durations quote the SAME cost", () => {
    // The shipped bug was two visible numbers for one concept. Pin agreement
    // by summing what the rows print and comparing it to what the header prints.
    const rotation: Rotation = [
      { characterId: A.id, actionType: "skill" },
      swapRow,
      { characterId: B.id, actionType: "burst" },
      { characterId: A.id, actionType: "swap" },
      { characterId: A.id, actionType: "normal" },
    ];
    for (const cost of COSTS) {
      const rowSum = rowTimings(rotation, byId, cost).reduce(
        (total, row) => total + (row.duration ?? 0),
        0,
      );
      expect(summarizeRotation(rotation, byId, cost).totalSeconds).toBeCloseTo(
        rowSum,
        10,
      );
    }
  });

  it("announceInsert quotes the configured cost, not the 0.60 default", () => {
    const result = insertAction(
      [{ characterId: A.id, actionType: "skill" }],
      1,
      B,
      "burst",
    );
    expect(result.autoSwapped).toBe(true);
    expect(announceInsert(result, "香菱", "burst", 0.4)).toContain("0.40 秒");
    expect(announceInsert(result, "香菱", "burst", 0.4)).not.toContain("0.60");
    expect(announceInsert(result, "香菱", "burst", 1.25)).toContain("1.25 秒");
  });

  it("a zero swap cost is priced as 0, not treated as absent", () => {
    // `?? DEFAULT` on a falsy-but-valid 0 is the classic defect here.
    expect(actionDuration(swapRow, B, 0)).toBe(0);
    const summary = summarizeRotation([swapRow], byId, 0);
    expect(summary.swapSeconds).toBe(0);
    expect(summary.totalSeconds).toBe(0);
  });
});

describe("orphaned rows and empty sequences", () => {
  const empty = new Map<string, CharacterDefinition>();

  it("summarizeRotation on an empty rotation reports zero, not an absence", () => {
    const summary = summarizeRotation([], byId, 0.6);
    expect(summary).toEqual({
      actionCount: 0,
      totalSeconds: 0,
      swapCount: 0,
      swapSeconds: 0,
      orphanCount: 0,
    });
  });

  it("an all-orphaned rotation reports totalSeconds null, not 0", () => {
    const rotation: Rotation = [
      { characterId: "ghost", actionType: "skill" },
      { characterId: "ghost", actionType: "normal" },
    ];
    const summary = summarizeRotation(rotation, empty, 0.6);
    expect(summary.totalSeconds).toBeNull();
    expect(summary.orphanCount).toBe(2);
  });

  it("an orphaned row contributes no time to later rows' start times", () => {
    const rotation: Rotation = [
      { characterId: "ghost", actionType: "skill" },
      { characterId: A.id, actionType: "skill" },
    ];
    const timings = rowTimings(rotation, byId, 0.6);
    expect(timings[0]?.duration).toBeNull();
    expect(timings[1]?.startTime).toBe(0);
  });

  it("an orphaned SWAP row is still counted as a swap by rowTimings but not by the summary", () => {
    // Documents the current split: `rowTimings` prices any swap, while
    // `summarizeRotation` skips orphans before the swap branch. Both are
    // defensible; pinning it so a change is deliberate.
    const rotation: Rotation = [{ characterId: "ghost", actionType: "swap" }];
    expect(rowTimings(rotation, empty, 0.6)[0]?.duration).toBe(0.6);
    const summary = summarizeRotation(rotation, empty, 0.6);
    expect(summary.swapCount).toBe(0);
    expect(summary.swapSeconds).toBe(0);
    expect(summary.totalSeconds).toBeNull();
  });

  it("actionDuration returns null, never a fabricated 0, for an unknown actor", () => {
    for (const actionType of ADDABLE_ACTION_TYPES) {
      const action: RotationAction = { characterId: "ghost", actionType };
      expect(actionDuration(action, undefined, 0.6)).toBeNull();
    }
  });

  it("actionDuration returns null for an action type the add bar cannot author", () => {
    for (const actionType of ["plungeLow", "plungeHigh"] as const) {
      expect(
        actionDuration({ characterId: A.id, actionType }, A, 0.6),
      ).toBeNull();
    }
  });
});

describe("determinism: identical inputs produce identical outputs", () => {
  it("every exported edit is a pure function of its arguments", () => {
    const types: readonly AddableActionType[] = ADDABLE_ACTION_TYPES;
    for (const rotation of enumerateRotations(2)) {
      const frozenInput = keys(rotation);
      for (const actionType of types) {
        const first = insertAction(rotation, 1, B, actionType);
        const second = insertAction(rotation, 1, B, actionType);
        expect(keys(second.rotation)).toEqual(keys(first.rotation));
        expect(second.actionIndex).toBe(first.actionIndex);
        expect(second.autoSwapped).toBe(first.autoSwapped);
      }
      // No exported edit mutates its input.
      expect(keys(rotation)).toEqual(frozenInput);
    }
  });
});
