import type { ArtifactSetDefinition } from "./types";
import { generatedArtifactSets } from "./generated/artifactSets";
import { generatedArtifactEffects } from "./generated/setEffects";
import type { GeneratedArtifactEffect } from "./generated/setEffects";

/**
 * Artifact sets, sourced from the generator.
 *
 * The previous 31-set table was hand-authored with no provenance header and no
 * generator, and an audit against Project Amber and Lunaris found 22 of its 60
 * set bonuses numerically contradicted -- including five sets whose Chinese
 * names and bonus text belonged to no real set at all. It has been replaced
 * wholesale by `generated/`, which is regenerated by
 * `scripts/generate-artifacts` and must never be hand-edited.
 */
export const allArtifacts: readonly ArtifactSetDefinition[] = generatedArtifactSets;

export const artifactsById: ReadonlyMap<string, ArtifactSetDefinition> = new Map(
  generatedArtifactSets.map((a) => [a.id, a]),
);

/**
 * Ids used by the retired hand-authored table, mapped to the generated id for
 * the SAME game set.
 *
 * These exist so a saved build or a shared link written before the regeneration
 * still resolves to the item the user actually chose. Every entry was confirmed
 * by matching the retired row's English set name against the source's own name
 * for that set id -- an alias is never a guess about which set was meant.
 *
 * `nighttime-whispers` is the one entry whose retired English name did not match
 * the source exactly ("...in the Forest" for the real "...in the Echoing Woods").
 * It is aliased anyway because the retired row is unambiguously set 15034: its
 * id, slug and release version all identify that set, and only its name and
 * bonus text were wrong.
 */
export const LEGACY_ARTIFACT_ID_ALIASES: ReadonlyMap<string, string> = new Map([
  ["crimson-witch", "crimson-witch-of-flames"],
  ["desert-pavilion", "desert-pavilion-chronicle"],
  ["echoes-offering", "echoes-of-an-offering"],
  ["emblem-severed-fate", "emblem-of-severed-fate"],
  ["flower-paradise-lost", "flower-of-paradise-lost"],
  ["fragment-harmonic", "fragment-of-harmonic-whimsy"],
  ["husk-opulent-dreams", "husk-of-opulent-dreams"],
  ["nighttime-whispers", "nighttime-whispers-in-the-echoing-woods"],
  ["scroll-hero-cinder", "scroll-of-the-hero-of-cinder-city"],
  ["shimenawa-reminiscence", "shimenawas-reminiscence"],
  ["tenacity-millelith", "tenacity-of-the-millelith"],
]);

/**
 * Look up a set by id, accepting a retired id.
 *
 * Normalisation (lowercase, strip anything outside `[a-z0-9-]`) is unchanged
 * from the previous implementation, so existing callers behave identically.
 */
export function findArtifact(id: string): ArtifactSetDefinition | undefined {
  const normalised = id.toLowerCase().replace(/[^a-z0-9-]/g, "");
  const direct = artifactsById.get(normalised);
  if (direct) return direct;
  const alias = LEGACY_ARTIFACT_ID_ALIASES.get(normalised);
  return alias ? artifactsById.get(alias) : undefined;
}

// ---------------------------------------------------------------------------
// Set bonuses (CONDITIONAL EFFECTS)
// ---------------------------------------------------------------------------
//
// Kept as a SEPARATE lookup from the reference records above, per MASTER-PLAN
// Wave 2: static build stats and conditional combat buffs must not travel in
// one record, or a conditional grant gets folded into the resolved panel and
// then applied again on the timeline.

export const allArtifactEffects: readonly GeneratedArtifactEffect[] =
  generatedArtifactEffects;

/** Every bonus belonging to one set, ascending by piece count. */
export function findArtifactEffects(
  setId: string,
): readonly GeneratedArtifactEffect[] {
  const resolved = findArtifact(setId);
  if (!resolved) return [];
  return generatedArtifactEffects.filter((e) => e.setSlug === resolved.id);
}

/**
 * The bonuses that a given piece count actually activates.
 *
 * Genshin's thresholds are inclusive and cumulative: four pieces grant BOTH the
 * 2-piece and the 4-piece bonus.
 */
export function activeArtifactEffects(
  setId: string,
  pieceCount: number,
): readonly GeneratedArtifactEffect[] {
  return findArtifactEffects(setId).filter((e) => pieceCount >= e.pieces);
}

/**
 * Only the bonuses a damage path may act on.
 *
 * FAIL CLOSED. "unimplemented" and "unverified" rows are excluded here rather
 * than at each call site, so forgetting the check cannot over-apply an effect.
 * Their numbers remain readable on the row for display and for future wiring.
 */
export function modelledArtifactEffects(
  setId: string,
  pieceCount: number,
): readonly GeneratedArtifactEffect[] {
  return activeArtifactEffects(setId, pieceCount).filter(
    (e) => e.support === "modelled",
  );
}
